export default function getUserData() {
  return [
    {
      id: 1,
      userName: "murad",
      name: "Amh Murad",
      password: "1234",
      role: "Admin",
      email: null,
      gender: "male",
    },
    {
      id: 2,
      userName: "joy",
      name: "nazmus joy",
      password: "1234",
      role: null,
      email: null,
      gender: "male",
    },
    {
      id: 3,
      userName: "anamul",
      name: "anamul haque",
      password: "1234",
      role: null,
      email: null,
      gender: "Female",
    },
    {
      id: 4,
      userName: "rakib",
      name: "rakibul islam",
      password: "1234",
      role: null,
      email: null,
      gender: "male",
    },
    {
      id: 5,
      userName: "hillol",
      name: "nasibul islam",
      password: "1234",
      role: null,
      email: null,
      gender: "Female",
    },
    {
      id: 6,
      userName: "hasan",
      name: "Al Mahamud Murad",
      email: null,
      password: "1234",
      role: "Super Admin",
      gender: "male",
    },
    {
      id: 7,
      userName: "mahamud",
      password: "1234",
      name: "Murad Hasan",
      role: "Moderator",
      email: null,
      gender: "male",
    },
    {
      id: 8,
      userName: "tunni",
      password: "1234",
      name: "hafiza tunni",
      role: "Moderator",
      email: null,
      gender: "Female",
    },
  ];
}
