export default function getUserData() {
  return [
    {
      userName: "murad",
      name: "Amh Murad",
      password: "1234",
      role: null,
      email: null,
      gender: "male",
    },
    {
      userName: "joy",
      name: "nazmus joy",
      password: "1234",
      role: null,
      email: null,
      gender: "male",
    },
    {
      userName: "anamul",
      name: "anamul haque",
      password: "1234",
      role: null,
      email: null,
      gender: "Female",
    },
    {
      userName: "rakib",
      name: "rakibul islam",
      password: "1234",
      role: null,
      email: null,
      gender: "male",
    },
    {
      userName: "hillol",
      name: "nasibul islam",
      password: "1234",
      role: null,
      email: null,
      gender: "Female",
    },
    {
      userName: "hasan",
      name: "Al Mahamud Murad",
      email: null,
      password: "1234",
      role: "admin",
      gender: "male",
    },
    {
      userName: "mahamud",
      password: "1234",
      name: "Murad Hasan",
      role: "moderator",
      email: null,
      gender: "male",
    },
    {
      userName: "tunni",
      password: "1234",
      name: "hafiza tunni",
      role: "moderator",
      email: null,
      gender: "Female",
    },
  ];
}
